[package]
name = "avalanche-network-runner-sdk"
version = "0.0.0"
edition = "2021"
rust-version = "1.61"
publish = true
description = "avalanche-network-runner-sdk in Rust"
license = "BSD-3-Clause"
homepage = "https://avax.network"
repository = "https://github.com/ava-labs/avalanche-network-runner-sdk-rs"

[dependencies]
log = "0.4.17"
prost = "0.10.4"
prost-types = "0.10.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio = { version = "1.18.2", features = ["fs", "rt-multi-thread"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
tonic = "0.7.2"
avalanche-proto = { version = "0.15.1" }

[build-dependencies]
# ref. https://github.com/hyperium/tonic/tree/master/tonic-build
tonic-build = "0.7.2"

[dev-dependencies]
assert-json-diff = "2.0.1"
env_logger = "0.9.0"

# serde_json is used in examples but fails cargo-udeps
[package.metadata.cargo-udeps.ignore]
normal = [ "serde_json" ]
