[package]
name = "avalanche-network-runner-sdk"
version = "0.0.0"
edition = "2021"
rust-version = "1.60"
publish = true
description = "avalanche-network-runner-sdk in Rust"
license = "BSD-3-Clause"
homepage = "https://avax.network"
repository = "https://github.com/ava-labs/avalanche-network-runner-sdk-rs"

[dependencies]
avalanche-proto = { version="1.7.11" }
log = "0.4.17"
prost = "0.10.3"
prost-types = "0.10.1"
tokio = { version = "1.18.1", features = ["fs", "rt-multi-thread"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
tonic = "0.7.2"

[dev-dependencies]
env_logger = "0.9.0"
